# Assignment #2

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('file.csv')
data = df['Data'].tolist()
size = len(df['Data'])

In [20]:
def calculatedistance(x1, x2, datalist, si):
    c_1 = [] 
    c_2 = [] 
    for x in range(0, si):
        c_1.append(abs(int(datalist[x] - x1)))
        c_2.append(abs(int(datalist[x] - x2)))
    return (c_1, c_2)

def checkc1c2(x, y):
    if x < y:
        return 1
    elif y < x:
        return 2
    elif x == y:
        return 3

In [21]:
import random
centralpoint1 = []
centralpoint2 = []
s = 'A'
precheck = []
currcheck = []
check = False
c1_ = []
c2_ = []
c1 = random.choice(data)
centralpoint1.append(c1)
c2 = random.choice(data)
centralpoint2.append(c2)
(c1_, c2_) = calculatedistance(c1, c2, data, size)
for i in range(0, size):
    result = checkc1c2(c1_[i], c2_[i])
    if result == 1:
        currcheck.append('c1less')
    elif result == 2:
        currcheck.append('c2less')
    elif result == 3:
        currcheck.append('equ')
precheck = currcheck
df[s + 'C' + str(1)] = c1_
df[s + 'C' + str(2)] = c2_ 
s = chr(ord(s) + 1)
while True:
    c1_ = []
    c2_ = []
    c1 = random.choice(data)
    centralpoint1.append(c1)
    c2 = random.choice(data)
    centralpoint2.append(c2)
    (c1_, c2_) = calculatedistance(c1, c2, data, size)
    currcheck = []
    for i in range(0, size):
        result = checkc1c2(c1_[i], c2_[i])
        if result == 1:
            currcheck.append('c1less')
        elif result == 2:
            currcheck.append('c2less')
        elif result == 3:
            currcheck.append('equ')
    check = False
    for j in range(0, size):
        if precheck[j] == 'c2less' and currcheck[j] == 'c1less':
            check = False
            break
        elif precheck[j] == 'c1less' and currcheck[j] == 'c2less':
            check = False
            break
        elif precheck[j] == 'equ' and currcheck[j] == 'c1less':
            check = True
        elif precheck[j] == 'equ' and currcheck[j] == 'c2less':
            check = True
        elif precheck[j] == 'equ' and currcheck[j] == 'equ':
            check = True
        elif precheck[j] == 'c1less' and currcheck[j] == 'equ':
            check = True
        elif precheck[j] == 'c2less' and currcheck[j] == 'equ':
            check = True
        elif precheck[j] == currcheck[j]:
            check = True
    df[s + 'C' + str(1)] = c1_
    df[s + 'C' + str(2)] = c2_ 
    s = chr(ord(s) + 1)
    if s == '[':
        s = 'A'
    if check == True:
        break
    precheck = currcheck

In [22]:
print("Central Points of C1: ",centralpoint1)
print("Central Points of C2: ",centralpoint2)

Central Points of C1:  [7, 5, 1, 10, 4, 4, 5, 2]
Central Points of C2:  [6, 10, 2, 7, 7, 3, 10, 2]

In [23]:
df

,Data,AC1,AC2,BC1,BC2,CC1,CC2,DC1,DC2,EC1,EC2,FC1,FC2,GC1,GC2,HC1,HC2
0,1,6,5,4,9,0,1,9,6,3,6,3,2,4,9,1,1
1,2,5,4,3,8,1,0,8,5,2,5,2,1,3,8,0,0
2,3,4,3,2,7,2,1,7,4,1,4,1,0,2,7,1,1
3,4,3,2,1,6,3,2,6,3,0,3,0,1,1,6,2,2
4,5,2,1,0,5,4,3,5,2,1,2,1,2,0,5,3,3
5,6,1,0,1,4,5,4,4,1,2,1,2,3,1,4,4,4
6,7,0,1,2,3,6,5,3,0,3,0,3,4,2,3,5,5
7,8,1,2,3,2,7,6,2,1,4,1,4,5,3,2,6,6
8,9,2,3,4,1,8,7,1,2,5,2,5,6,4,1,7,7
9,10,3,4,5,0,9,8,0,3,6,3,6,7,5,0,8,8

In [17]:
df.to_csv('result.csv', index=False)